### ISSUE TITLE
Needs method to list all collections

### ISSUE THREAD

**Issue by DerekGloudemans** [yanb514/i24_database_api#3]
Essentially ```[col["name"] for col in list(gtd.db.list_collections())]``` but this is quite clunky and requires having a specific db client targeting a specific collection. 

In general it might be nice to add some basic database management that doesn't require targeting a specific collection

**Comment by yanb514** [comment]
added a basic way to connect to the client (`dbc = DBClient(**db_param)`) such that you can connect to any arbitrary databases by `dbc.client[db_name].list_collection_names()`
